spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rest_with_spring_boot_marcos
    username: postgres
    password: Henrique7&
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      show-sql: false